### ISSUE TITLE
Naming scheme

### ISSUE THREAD

**Issue by gagern** [twolfson/fixture-dir#1]
The naming scheme currently implemented is _insecure_ and broken for several other reasons as well. The main problem is that you have a deterministic top level name, and only inside that a possibly non-deterministic second name.

On a multi-user system, the top level directory (e.g. `/tmp/foo`) might already exist, but belong to some other user. Depending on your situation, this could mean your fixture run interfering with that of someone else, or your fixture run failing because someone else owns a directory of that name which is not world-writable, or perhaps the owner has set strange attributes for that directory (like sticky group bit or some ACLs) which make files created inside that directory writable to him. If the fixture executes any code in such a temporary directory, this could lead to one user gaining the privileges of another.

All of the above is theoretic for me, since in practice things fail in the common use case: if the named top level directory does not exist already, and you want to copy data from somewhere else and didn't name the subdirectory explicitely, then `wrench.copyDirRecursive` is used instead of `mkdirp`, and will fail since the top level directory under which it should create the child directory does itself not exist.

All things considered, I believe it would be better if the top level directory were non-deterministic, perhaps with a prefix to indicate where it belongs. In my use case I've ended up using [temp](https://www.npmjs.com/package/temp). It isn't using [`mkdtemp`](http://linux.die.net/man/3/mkdtemp) either, but it puts so much entropy in the name that a clash is _very_ unlikely. And its `track()` method to clean up any left-over stuff automatically at exit is nice, too. Perhaps you want to build on that?

**Comment by twolfson** [comment]
Ah, you are correct. The current implementation does not do any valid checking of folder existence/ownership before working within it. At the time I wrote this library, I was not aware of the security implications and we should fix them.

I don't exactly understand your deterministic/non-deterministic terminology. Are you implying that `/tmp` or its variant isn't guaranteed to exist on an OS? I believe `tmp` is covering that case fine:

https://github.com/raszi/node-tmp/blob/v0.0.23/lib/tmp.js#L43-L54

If not, can you provide more examples? (e.g. example paths and where the problem lies in those paths).

**Comment by gagern** [comment]
I use “deterministic” to mean “non-random” and vice versa. And I wasn't concerned about the existence of `/tmp` itself, but the directory below that. The one you have to pass to the `FixtureDir`, which I called “top-level”, as opposed to the one you may pass to `mkdir` which I called “subdirectory”.

Let's have an example. If I simply want any directory for my code, which is for the tests of module “foo”, then I'd do

```
var fixtureDir = new FixtureDir("foo-tests");
fixtureDir.mkdir(callback);
```

and get something like `/tmp/foo-tests/16952H0dMU15N4tWk`. Now the problem here is `/tmp/foo-tests`. It might exist, be owned by someone else, and have strange properties. It could be a symlink, or be set up so that filles dropped in there become writable by someone else.

I propose you don't include a trailing slash with your prefix. And you leave directory creation to `tmp.dir`. That way you end up with some `/tmp/foo-tests-16952H0dMU15N4tWk` which is guaranteed to be newly created, since `mkdir` fails for existing dirs. It also resides directly in `/tmp`, which in turn should not have any evil attributes set if the system is set up in a regular way. It is created with access only for the current user, so anything you do inside is safe as well. If the user passes a folder name to `mkdir`, then you can set up a folder of that name _inside_ the randomly named folder you just created.

When I first compared the `tmp` and `temp` modules, I hadn't realized that `tmp` did such randomization as well, nor that it's already used in your code. Now the two seem pretty much equivalent, and sticking with `tmp` is fine. It looks as if `tmp` would by default delete the directories it created at exit, just like `temp` can do with the `track()` setting, so switching to `tmp.dir` is enough to give you that feature as well.

**Comment by twolfson** [comment]
Ah, I understand now. That sounds like a good proposition. I am going to take a look at getting those changes in place.

**Comment by twolfson** [comment]
After starting to dig into the code and refresh my memory further, I am realizing that this was initially built to make debugging tests easy as well. Tests should be cleaning up their `/tmp` folders every time which wouldn't lead to this as a problem. Can you elaborate on the use case more?

**Comment by gagern** [comment]
Let's assume that project “foo” contains the following test case:

``` js
var fs = require("fs"),
    path = require("path"),
    child_process = require("child_process"),
    FixtureDir = require("fixture-dir"),
    fixtureDir = new FixtureDir("foo-tests");

fixtureDir.mkdir({}, function(err, dir) {
  if (err) throw err;
  // simulate unpacking some tarball or similar
  fs.writeFile(path.join(dir.path, "configure"), "echo All is well");
  setTimeout(configure.bind(null, dir), 5000);
});

function configure(dir) {
  child_process.spawn("/bin/sh", ["./configure"], {
    cwd: dir.path,
    stdio: "inherit"
  }).on("close", function(code) {
    dir.destroy();
  });
}
```

# Scenario 1: unintentional clash

Alice and Bob work on the same machine on that project. At some time, Alice runs the above test. Some time later, Bob does the same. He receives an error message:

```
Error: EACCES, mkdir '/tmp/foo-tests/1961196q1rkw'
    at Error (native)
```

That's because `/tmp/foo-tests` exists, belongs to Alice and isn't writable by anyone but Alice.

# Scenario 2: malicious attack

Bob and Eve work on the same machine. Bob is the sole developer of the project containing the test above. The machien is set up to clear the `/tmp` directory every night. Eve runs the following shell script before Bob starts his work:

``` sh
mkdir /tmp/foo-tests # new directory belongs to Eve, so she can do stuff
chmod a+w /tmp/foo-tests # but Bob can write, so he won't notice anything
setfacl -d -m other::rwx /tmp/foo-tests/ # newly created files become world-writable!
while ! [ -e /tmp/foo-tests/*/configure ]; do :; done # wait till Bob runs his test
sleep 1 # wait till the write is complete so we are the last to write that file
echo "echo You got hacked" > /tmp/foo-tests/*/configure # overwrite 
```

Now Bob will unintentionally execute the code Eve wrote to his file. It might be installing Eve's ssh public key in Bob's `~/.ssh/authorized_keys` file, so Eve can log in as Bob and do anything from there.

**Comment by twolfson** [comment]
I think we are conflating 2 issues in a single issue thread.
- Naming (e.g. 2 users are attempting to talk to the same fixtured folder for tests)
- Permissions (e.g. `/tmp/foo-tests` should be owned by user running tests and only writable by them as well)

I agree that we should patch permissions (scenario 2). With respect to naming (scenario 1), my concern is that we lose the ease of debugging since as a developer I need to jump folders every time I run tests. To reiterate my question, is scenario 1 hypothetical or is it actually occurring for you?

**Comment by twolfson** [comment]
I am also wondering if scenario 1 is rare enough that we could have an option for developer's to provide the randomized string themself. For example:

``` js
// Generate fixture dir with random name (e.g. `foo-tests-1pfn788c684`)
new FixtureDir('foo-tests-' + (Math.random() * 1e16).toString(36))
```

**Comment by gagern** [comment]
Those two issues have a single solution. The only _portable_ way I can think of to ensure sane permissions is by creating the directory from scratch.

Can you elaborate on why you'd have to “jump folders”? Is it in some shell, or in the test suite? Is it while the test is running, or afterwards, or if it failed? Is it to repeatedly execute the same commands, so that a `*` in the path could take care of the unknown name? The subdir is expected to go away after each test, so you shouldn't cd to that if the tests completes successfully, right?

So far, scenario 1 isn't an issue for me, since I haven't started using fixture-dir on a large scale due to the issues here, and since I'm mostly using my computer just for myself. Things would become different if I'd set up some CI which runs as a different user.

More importantly, though, I don't feel comfortable publishing software when I know that users building that software might be vulnerable due to an issue I know about. So issue 2 is my main concern.

**Comment by twolfson** [comment]
Ah, concurrent CI tests under the same user is definitely a valid user case and scenario for 1 (e.g, Jenkins where we don't have VMs).

Even while random names obscures the problem we should still have programmatic enforcement of permission checking (if a folder already exists). For example, a hacker could fill all possible folder names or somehow predict our random seed.

By "jump folders", I mean that I sometime have a terminal open in the fixtured directory and inspect its contents (e.g. I am in `/tmp/foo-tests` and look at `cd bar/` to see what the git status is).

**Comment by twolfson** [comment]
For concurrent tests, sometimes CI will provide known different variables to prevent collisions. In those scenarios then a user could provide that random string from `process.env` whereas our random generation might not be guaranteed to avoid collisions =/

**Comment by twolfson** [comment]
Alright, whipped up a branch that enforces users/permissions. Does this look good to you?

https://github.com/twolfson/fixture-dir/compare/ddf041d3eb64783a7b191e22c735cc4c62901785

**Comment by gagern** [comment]
ddf041d3eb64783a7b191e22c735cc4c62901785 looks safer at least.

It won't address scenario 1 above, since if the folder has the wrong owner, you error out. But there is little you can do, if you insist on your naming convention, since you can hardly delete a folder owned by somone else. Personally I'd prefer `desiredMode = 0700` over `desiredMode = 0777 & (~process.umask())` since that way the code I'm testing can do unsafe stuff in there, like executing code in world-writable files, and I won't have to worry about it. I guess things would break e.g. on some FAT-based file system, where you don't have ownership information.

I guess I'll stick to `tmp.dir` or `temp.mkdir` since I prefer the auto-cleaning and the way scenario 1 won't happen. But that's because I never expect to change to the fixture dir manually, so I don't care what it's named. It's a matter of taste and usage scenario, no longer a security issue.

**Comment by twolfson** [comment]
Can you elaborate on your `desiredMode` notes further? With respect to directories, read allows for listing files and execute alllows for accessing said files. They aren't attached to the permissions of the files themselves.

With respect to randomizing naming, I am leaning toward making it easier to opt-in to randomization than not. What's your opposition to the randomization snippet I posted earlier?

``` js
// Generate fixture dir with random name (e.g. `foo-tests-1pfn788c684`)
new FixtureDir('foo-tests-' + (Math.random() * 1e16).toString(36))
```

**Comment by twolfson** [comment]
Closing issue due to inactivtity
